### ISSUE TITLE
Can't move past Configuration (/settings)

### ISSUE THREAD

**Issue by marklysze** [mbarinov/repogpt#4]
I've set it up in a DevContainer and installed PostgreSQL with Pgvector. It's up and running, however once I enter my OpenAI API Key and GitHub API Key, hit Save, it pops up to say that they were saved but the page doesn't navigate anywhere else. I tried clicking on the "Import Repos" button, the "Repositiories" and "Main" menus but it stays on the `/settings` Configuration screen.

Any ideas?

**Comment by mbarinov** [comment]
The issue has been fixed. There was an issue with built-in Next.js cache for pages. Can you confirm it @marklysze ?

https://github.com/mbarinov/repogpt/commit/226fe82d2d31343aeba9c76ee3789e9d859c17c3

**Comment by marklysze** [comment]
> The issue has been fixed. There was an issue with built-in Next.js cache for pages. Can you confirm it @marklysze ?
> 
> [226fe82](https://github.com/mbarinov/repogpt/commit/226fe82d2d31343aeba9c76ee3789e9d859c17c3)

Thanks @mbarinov, a `git pull` and a `pnpm build` and it got through it. Appreciated and thanks for creating this!
